### ISSUE TITLE
Dark theme support

### ISSUE THREAD

**Issue by pandasauce** [danigargu/deREferencing#1]
This is what the registers window currently looks like on dark theme:

![](https://i.imgur.com/jrtXGsM.png)

Very difficult to read. Is there any way to pick a less bright background color for this widget?

**Comment by danigargu** [comment]
Ops! I didn't try it with a dark theme. The background color can be modified from the config.py file, or even deactivate, setting the variable `highlight_changes`  to `False`.

```
highlight_changes = False
highlight_color   = 0xFFD073
```

What darktheme do you use? I would like to try it

**Comment by pandasauce** [comment]
Color `0x795e3e` seems to work well with the dark theme while also matching the current line's highlight color from the disassembly view. I am using the stock dark theme (Options->Colors->Current theme->dark)
