### ISSUE TITLE
Can't display register flag values, no horizontal scrollbar available

### ISSUE THREAD

**Issue by CaledoniaProject** [danigargu/deREferencing#19]
I'm running this plugin on IDA 7.6 latest. The value of register flags is not displayed and there's no horizontal scrollbar.
I've tried to drag the left bar to enlarge the right pane, but it's not draggable.

![screenshot 2021-05-23 at 10 03 27 PM](https://user-images.githubusercontent.com/1357701/119263723-c7a75e80-bc12-11eb-9aa7-1627097b0f6c.jpg)

When I manually scroll horizontally, the register value is visible:

![screenshot 2021-05-23 at 10 03 32 PM](https://user-images.githubusercontent.com/1357701/119263725-ca09b880-bc12-11eb-9dd7-518eed47a352.jpg)

Was it a bug?

**Comment by danigargu** [comment]
This is due to your resolution or font size in IDA. You can expand the flags width in the following line: https://github.com/danigargu/deREferencing/blob/master/dereferencing/views/registers.py#L426

I will try to improve this, thanks! :)
